---

- hosts: localhost
  gather_facts: false
  vars:
    openshift_host: 'https://kubernetes.default'
    openshift_skip_tls_verify: '{{ skip_tls_verify | default(false) | bool }}'
    enable_dangerous_logs: false
  tasks:
    - when: admin_api_token is not defined
      block:
      - command: oc whoami -t
        register: token
      - set_fact:
          openshift_token: '{{ token.stdout }}'
      no_log: '{{ not enable_dangerous_logs }}'
    - when: admin_api_token is defined
      set_fact:
        openshift_token: '{{ admin_api_token }}'
      no_log: '{{ not enable_dangerous_logs }}'
    - name: Authenticate with OpenShift via token
      shell: |
        oc login {{ openshift_host }} \
          --token {{ openshift_token }} \
          --insecure-skip-tls-verify={{ openshift_skip_tls_verify | default(false) | bool }}
      no_log: '{{ not enable_dangerous_logs }}'
    - command: oc whoami
      register: user

    - name: Set facts for variables that cannot be defined if they are not set
      set_fact:
        '{{ item[0] }}': '{{ item[1] }}'
      when: item[1] is not None
      with_items:
        - [[pg_hostname, '{{ lookup("env", "DB_HOST") | default(awx_postgresql_hostname, true) | default(None) }}']]
        - [[pg_database, '{{ lookup("env", "DB_NAME") | default(awx_postgresql_dbname, true) | default(None) }}']]
        - [[pg_username, '{{ lookup("env", "DB_USER") | default(awx_postgresql_user, true) | default(None) }}']]
        - [[pg_password, '{{ lookup("env", "DB_PASSWORD") | default(awx_postgresql_password, true) | default(None) }}']]
        - [[pg_port, '{{ lookup("env", "DB_PORT") | default(awx_postgresql_port, true) | default(None) }}']]

- import_playbook: /usr/share/awx_installer/installer/install.yml
  vars:
    dockerhub_base: '{{ awx_image_org | default("ansible") }}'
    dockerhub_version: '{{ awx_image_tag | default("latest") }}'
    pg_volume_capacity: '{{ awx_postgresql_volume_capacity | default("5", true) }}'
    openshift_host: 'https://kubernetes.default'
    openshift_user: '{{ user.stdout }}'
    openshift_skip_tls_verify: '{{ skip_tls_verify | default(false) | bool }}'
    openshift_pg_emptydir: '{{ postgresql_emptydir | default(false) | bool }}'
    awx_openshift_project: '{{ namespace }}'
    awx_kubernetes_namespace: '{{ namespace }}'
