---

- hosts: localhost
  gather_facts: false
  tasks:
    - command: oc whoami
      register: user
    - command: oc whoami -t
      register: token
      no_log: true
    - name: Authenticate with OpenShift via token
      shell: |
        oc login {{ openshift_host }} \
          --token {{ openshift_token }} \
          --insecure-skip-tls-verify={{ openshift_skip_tls_verify | default(false) | bool }}
      vars:
        openshift_host: 'https://kubernetes.default'
        openshift_token: '{{ token.stdout }}'
        openshift_skip_tls_verify: '{{ skip_tls_verify | default(false) | bool }}'

- import_playbook: /usr/share/awx_installer/installer/install.yml
  vars:
    dockerhub_base: '{{ awx_image_org }}'
    dockerhub_version: '{{ awx_image_tag }}'
    pg_hostname: '{{ lookup("env", "DB_HOST") | default(awx_postgresql_hostname, true) | default("") }}'
    pg_database: '{{ lookup("env", "DB_NAME") | default(awx_postgresql_dbname, true) | default("awx") }}'
    pg_username: '{{ lookup("env", "DB_USER") | default(awx_postgresql_user, true) | default("awx") }}'
    pg_password: '{{ lookup("env", "DB_PASSWORD") | default(awx_postgresql_password, true) | default("awxpass") }}'
    pg_port: '{{ lookup("env", "DB_PORT") | default(awx_postgresql_port, true) | default(5432) }}'
    pg_volume_capacity: '{{ awx_postgresql_volume_capacity | default("5", true) }}'
    openshift_host: 'https://kubernetes.default'
    openshift_user: '{{ user.stdout }}'
    openshift_token: '{{ token.stdout }}'
    openshift_skip_tls_verify: '{{ skip_tls_verify | default(false) | bool }}'
    openshift_pg_emptydir: '{{ postgresql_emptydir | default(false) | bool }}'
    awx_openshift_project: '{{ namespace }}'
    awx_kubernetes_namespace: '{{ namespace }}'
